"""Async repository protocols and the unit-of-work port. Services depend only on these.

Query objects carry filters, sort and pagination, so services never build storage-specific
queries and a SQL implementation can honour the same contract (ADR-202, NFR-224).

Task 3 adds, and only adds (ADR-303, ADR-314):
- `for_update` on the reads that precede a locked change (BR-306);
- the `UnitOfWork` port, the transaction boundary of every operation (BR-305);
- `progress_for_many`, `totals` and `count` so lists and the dashboard use one aggregate query
  each instead of one query per row (BR-304, NFR-304);
- `add_many`, so the seed can bulk-load the `xl` profile.
"""

from collections.abc import Sequence
from datetime import date, datetime
from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from app.domain.enums import ProjectStatus
from app.domain.models import (
    Activity,
    AiRequest,
    Profile,
    Progress,
    Project,
    RefreshToken,
    Task,
    User,
)
from app.domain.queries import (
    ActivityQuery,
    Page,
    ProjectQuery,
    TaskQuery,
    TaskTotals,
    UserQuery,
)
from app.domain.visibility import ReadScope


class TransientStoreError(Exception):
    """A deadlock, lock timeout or statement timeout: worth retrying, then a 503 (section 7)."""


class UserRepository(Protocol):
    async def get(self, user_id: UUID, *, for_update: bool = False) -> User | None: ...
    async def get_by_email(self, email: str, *, with_hash: bool = False) -> User | None: ...
    async def list(self, query: UserQuery) -> Page[User]: ...
    async def add(self, user: User) -> User: ...
    async def add_many(self, users: Sequence[User]) -> None: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> bool: ...
    async def count_leads(self, *, for_update: bool = False) -> int: ...


class ProfileRepository(Protocol):
    async def get(self, user_id: UUID, *, for_update: bool = False) -> Profile | None: ...
    async def get_many(self, user_ids: Sequence[UUID]) -> dict[UUID, Profile]: ...
    async def add(self, profile: Profile) -> Profile: ...
    async def add_many(self, profiles: Sequence[Profile]) -> None: ...
    async def update(self, profile: Profile) -> Profile: ...
    async def replace_skills(self, user_id: UUID, skills: Sequence[str]) -> None: ...
    async def delete(self, user_id: UUID) -> None: ...


class ProjectRepository(Protocol):
    async def get(self, project_id: UUID, *, for_update: bool = False) -> Project | None: ...
    async def list(self, query: ProjectQuery) -> Page[Project]: ...
    async def add(self, project: Project) -> Project: ...
    async def add_many(self, projects: Sequence[Project]) -> None: ...
    async def update(self, project: Project) -> Project: ...
    async def delete(self, project_id: UUID) -> bool: ...
    async def count_by_owner(self, owner_id: UUID) -> int: ...
    async def count(
        self, statuses: Sequence[ProjectStatus] = (), scope: ReadScope | None = None
    ) -> int: ...
    async def owned_ids(self, owner_id: UUID) -> set[UUID]: ...


class TaskRepository(Protocol):
    async def get(self, task_id: UUID, *, for_update: bool = False) -> Task | None: ...
    async def list(self, query: TaskQuery) -> Page[Task]: ...
    async def add(self, task: Task) -> Task: ...
    async def add_many(self, tasks: Sequence[Task]) -> None: ...
    async def update(self, task: Task) -> Task: ...
    async def delete(self, task_id: UUID) -> bool: ...
    async def progress_for(self, project_id: UUID) -> Progress: ...
    async def progress_for_many(self, project_ids: Sequence[UUID]) -> dict[UUID, Progress]: ...
    async def totals(self, today: date, scope: ReadScope | None = None) -> TaskTotals: ...
    async def assigned_project_ids(self, user_id: UUID) -> set[UUID]: ...
    async def unassign_user(self, user_id: UUID) -> int: ...
    async def assigned_counts(self, user_id: UUID) -> tuple[int, int]: ...


class ActivityRepository(Protocol):
    async def add(self, activity: Activity) -> Activity: ...
    async def add_many(self, items: Sequence[Activity]) -> None: ...
    async def list(self, query: ActivityQuery) -> Page[Activity]: ...


class RefreshTokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> RefreshToken: ...
    async def get_by_hash(
        self, token_hash: str, *, for_update: bool = False
    ) -> RefreshToken | None: ...
    async def mark_used(self, token_id: UUID, at: datetime) -> None: ...
    async def revoke_family(self, family_id: UUID, at: datetime) -> int: ...
    async def revoke_user_except(
        self, user_id: UUID, keep_family: UUID | None, at: datetime
    ) -> int: ...
    async def delete_expired(self, before: datetime) -> int: ...


class AiRequestRepository(Protocol):
    async def lock_quota(self) -> None: ...
    async def add(self, request: AiRequest) -> AiRequest: ...
    async def get(self, request_id: UUID) -> AiRequest | None: ...
    async def list_recent(self, limit: int = 100) -> list[AiRequest]: ...
    async def update(self, request: AiRequest) -> None: ...
    async def count(self, *, since: datetime, user_id: UUID | None = None) -> int: ...
    async def oldest_at(
        self, *, since: datetime, user_id: UUID | None = None
    ) -> datetime | None: ...
    async def delete_older_than(self, cutoff: datetime) -> int: ...


class UnitOfWork(Protocol):
    """One transaction: everything inside commits together or rolls back together (BR-305)."""

    @property
    def users(self) -> UserRepository: ...

    @property
    def profiles(self) -> ProfileRepository: ...

    @property
    def projects(self) -> ProjectRepository: ...

    @property
    def tasks(self) -> TaskRepository: ...

    @property
    def activity(self) -> ActivityRepository: ...

    @property
    def refresh_tokens(self) -> RefreshTokenRepository: ...

    @property
    def ai_requests(self) -> AiRequestRepository: ...

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...


__all__ = [
    "ActivityQuery",
    "ActivityRepository",
    "AiRequestRepository",
    "Page",
    "ProfileRepository",
    "ProjectQuery",
    "ProjectRepository",
    "RefreshTokenRepository",
    "TaskQuery",
    "TaskRepository",
    "TaskTotals",
    "TransientStoreError",
    "UnitOfWork",
    "UserQuery",
    "UserRepository",
]
